language: objective-c

before_script: 
- gem install xcpretty

script:
- xcodebuild -project Tests/VLRNotificationScheduler/VLRNotificationScheduler.xcodeproj -scheme VLRNotificationSchedulerTests -sdk iphonesimulator test | xcpretty -c ; test ${PIPESTATUS[0]} -eq 0
